### ISSUE TITLE
07-Moon-Phase-Clock/PIO/platformio.ini

### ISSUE THREAD

**Issue by rezz506** [nishad2m8/T-Display-S3-YT#3]
Hi there - is there any way to change this code to work with the T- Display-S3 PRO? 

Changed resolution to the following: 
/*Change to your screen resolution*/
static const uint16_t screenWidth = 480;
static const uint16_t screenHeight = 222;

Everything within serial monitor seems to be fine. Just a black screen whenever booted up.

**Comment by nishad2m8** [comment]
If the serial ok logic is working, changing the resolution won't fix it. t-display S3 s resolution is 320x170. moon phase images (170x170) and everything else are based on this resolution.

![Moon_3](https://github.com/nishad2m8/T-Display-S3-YT/assets/53113272/2f11ea7d-2e92-47db-a1fc-5e7e8c20b4a3)

**Comment by rezz506** [comment]
Thank you for your response - am very new to all of this. After some more troubleshooting I don't believe resolution scaling was the issue anymore. I'm having trouble getting images to display on the PRO using TFT_eSPI library. When using Arduino_GFX library I seem to be able to get simple images like circles and squares to display.

**Comment by nishad2m8** [comment]
i don't have any idea with Arduino_GFX. in squareline studio exports it using lvgl and TFT_eSPI library
